{% set version = "0.8.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggrepel
  version: {{ version|replace("-", "_") }}

source:
  fn: ggrepel_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggrepel_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggrepel/ggrepel_{{ version }}.tar.gz
  sha256: d5d03a77ab6d8c831934bc46e840cc4e3df487272ab591fa72767ad42bcb7283

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-ggplot2 >=2.2.0
    - r-scales >=0.3.0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-ggplot2 >=2.2.0
    - r-scales >=0.3.0

test:
  commands:
    - $R -e "library('ggrepel')"           # [not win]
    - "\"%R%\" -e \"library('ggrepel')\""  # [win]

about:
  home: http://github.com/slowkow/ggrepel
  license: GPL-3
  summary: Provides text and label geoms for 'ggplot2' that help to avoid overlapping text labels.
    Labels repel away from each other and away from the data points.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
