travis:
  secure:
    BINSTAR_TOKEN: Xht7s6g5pykm4eyKWuG3C/wpJUdfKtmwCn1S61GtjNffYzNj6Ur57VXiMs01SxQUx7NKvbL4lEbnTV7OWcjkXJ/F3LuoQTU7kg+IKPxTRBcBUDd+slatRnU/IAkd+BjG1rq/CiQasNWqN9L0N9yXysEWiTIsZDwn5U8z+Hj6RR16L/7K+nwDX58EcG0N7Q4KNcEKCX2YpGCahCNXF/MH495tqIwk6CjDSq+CyKNeufgCiKHufOfzPg3h4mcggxwWF3BB6fgGi6oEqpgXaplbRr5YAlB1x/UOMecomjcFByIbeXEnsuNuQgogSoM1D5gtqJqYKTielzqplljf5Tb94OIpehq/DtMwpRFSNXDbePB9VoA7jT3pO2QSdbZn+VvNrVBPkgFXI/3tPI5zl9+oe6gE+JyOlHKFRfwW2xrGXMppQ3KG6jtqSGCz76mOlgRV5RtYzg3b7n7u1xHlchyqQ6kagzMwr95eLfI69WtbLRiZ0ud8OOPmg8a/U5l0/9xwKE2zsorzSQpZForp6nb5qTb+0IpI+cDY6JTWAxCoEc35hmmf5c/4MNci4WapqLDWUD+vHugwXFo9WdaZo1bn0CJs0zo3DkWaKUVLHm5255MPGxuuvv1TeXAI791kNHoyzaictVmfKGCOXRyOfwtuuDPPu9p/ZcaDvxVlBW3OdLY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
