travis:
  secure:
    BINSTAR_TOKEN: dZLhzwYbsvMER4AsI+Ldi+Y8EpOydncUrUBR6xmiElrNdmH07vz3yBIKwhcQ8zuWZYVTAVd6lxrCDgT7nbnt8Tja9jjZWohJkS63u9k6+zE1YNFQ6JtK1mc/9zZxl6JGEInh+KUO+J4c92nkhV1d+DlUxS39M98+u9FjsaGQmecIIMdww8CebMQwzxxta1lJvpnXRwgJf9eLlABDOiTTfVMB1lA2mR01kaw7yb56nR6+cOLf82JYMdewqn32W5agbAl/vdcCIj0HAqox0a9VpIYXddPhiHRSP6Tg8St64bUp+v3OYT2qPbkHthnOljI4Gyp6QdVjgMfgm6vK15ZzcE6dAkj4UPCU60186IDrp7qfxGP51pzmm1Ebm3htmGs+cIjy9sZzXiejIh6tXkbSS0dwSjTKTB87EozIdlA0Gy0HrovYiYoggDIfinb3VoonqhESGGJxduOGQEl/i6WeifFQHatXDnPdvE6HwaNDhGPR3d70CjKP4bNmaCQOD9mayd89npV2OWh9F0dN7YnS5aXZFA2PAR37eE2HuYKt6OxfMuMuVuXfH3ZyK9WOpwtOyjuwczTYhbA85uJ9aZbPPPdF6yKxMwY7kBc1I3JuaNSlju3+/WzeTnwWNIKvLRYV6/baiidOlybvVRC9wjXRrzPWSFuZDbOAk1k7h6XV87Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
