travis:
  secure:
    BINSTAR_TOKEN: 1zw+IC/PsBdkl5ArPrxIybULpkd0O4fkRnO2TRbbrJqymUMdQuEqDM1T7pAwCKq1hpSJ7u2dLow0SWtv1SqQpYOSeSAHIuGwGxrV9WX62VGdzQremDbL+xGOE6eBFTsYhDUs6WhyZgzgMR4jD3ZvrhNCjHrEwDvqJkPFlUy61VBgPwAZ6z41fwtLD8nZR/4qu+hHGKj/CQFjyVx5Jk/NyLGst1tm4U4bB4ATRkctR8oDsfHo0btDg6fUw9W/MS9yNYAM5vLY5SNluxjiG8hRH242kHiqEkG1L7SQ9S/2iV6EcmJjnAdQaWp5RP5wc4RzeteQb81ew/cuV49d07L8Mj6vF1YueGXO7YoCtmqDNXAuHYoKzelscHy86YwFjybvATMCXq3en6fSlxM+yqb2tQOT7ftUsl20gpEjmeIZsk3QDnuyV6wzEukG69xpcTQUMMI3NhEyHM5PkvyCYbcc7eA0S2wfR6am+c0O/WxU3hP+aCZPiFGh3dyt6Nzhr4ZyevrId9PMIkzoyLOtSf/qNxicicC5ytfFIdyyXbEybxV1OoFFe9i9rhzeJ88/ZANztgIlzr1C7FnZS/ndIPc4afc7RE0+FhHUgJd28CyF9JQ0FIsKzN9iCLD584Tdhn/HRmOE9/wNDPOKTtGrlaIY+rVH0iuzFKf5OyiAizKE+mE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
