travis:
  secure:
    BINSTAR_TOKEN: PqzZ4C91pWLSeYyBTnn8OqGVO45CeQ0z4C9AxG083i156NC+F/3n7c50vsSJHV65hyWoI6vSwNI4c37/n9JV1r8XR8s4XN3rDB16UoqE6jFTfPDLnav7uSy8OR55X6zemmfhT0YjIzLF9pvj0iD3+AxWzXVgvOnJzSScNFch5/0rNQz713ibj7P9RSRrtbSGa8bj8In8Q5Wfy6umz9k6ZpsgtbbnLZmWEEe0K6saiNwsFwpIZFd2F3zJAITc0slZqcIAxJQ7qh0hB6Y1cgFUSp8qwVuYuT3R8RaWYxJP30tOmIZYy+/ZOZT2EY8k2MkZuEf19ES8WyPBowy5jZ3zOKIjtOUVbhDBKrMoNGUo/R510aP6JqYASa6oyhmIbDGyeJ1y42RYZNf1Xu1x+pWxcodw+NZpSDN4zCvJJ2ytbrqvqDxwfz37AjwJjnCCFiLdX6up+D2Y0FX6XFVj1lykPBqYtXjmvF/seeqvjsc8U4Uu1ehnHjRfEvXrGr8I2w/7opoirfVVQuNC0HoNkWMYyuN0twipcfKjwRV0CRiKUJaQCoFJ7KfzfEEc2UvmHEzY+6BETF+DLZqGYpcHvS95zfPA7GaNvG8J0fsI6Tupk06N/BOS3KdAd9LSXkeugoM79fT8AZB58mgwhR4sIG79lGuxPgoatBqk19DW4B2ylCc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
