travis:
  secure:
    BINSTAR_TOKEN: qhrnZi7h6NL6i9o7h6ry04qah6tZpIbPsuhtTX1/reZBDW1B6ug8UdFp/upJAovcM2QsBD1AUWQlaWFXQKh//OUg4Pwhwc83v6X4wa7QvsqKUYOBun5HeVrk0/gzgDZMPOvPwQbxwxY/WK++qwkSUKBgEiTSuDxaobse4uvkpTE1zq8PjYGZkkefFcJyeC0TwSvffAa0b0XOKJOx9mR8ugwBzTIe2t1YCdeKmOArRhGOWN72czk84Kvlzy0z0Gs2DyYXqLYfQnAV9f9ZyyfcXliEtEdPkW0ngRFEbRuYtxFCRIERMvRvPBl0Bzx6jm6f+ebcQUpOmb8EtCCZwyE37TzNRNPAKK/KdoygamtEUFRIMJzXtapCanDWk5575uhmeWp7nMBWCDmZOhVl6CqDsoaiCtoPqfkPeZG14CSVFXv5pbHfYJYMowo+qYntrSJ14MvDw1YNndKBDGZYWr2wjScumzjv1MIFHquDSY06oH9BpwtojwUPuHrVTUTdYdeYG+HhJH6BR9XgE0UqaNwNxC4yk1fWhDR3RJoPQjmO7viZyGqtVYLLf843K2L6Ty1Ef52unvisL53p4k4444J4c65bHCBqj1VZ3ewhpE9TgNpRcd8KGbgPpoVgL56CBtxp98pI7DcImjUHLvtcdLCr24ItrgG26SQ2+7hL0AJPpyM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
