travis:
  secure:
    BINSTAR_TOKEN: ww6t9TLZGeCcNCPznAs+sErACLhoR9sGwU5893zVO9rfOufHAYPEifl9YfKw8J37cwjBEbOmUyqpdeJavn45UvjH0SE8WRkglznZhHm9fQNxBZ+LCVqvMHDx7fRKMFX2OMjwIJzv9CxTOVybwqaUQvQSixxone8PJZtlHU/i1huVvIQntOhE5d7hEt2zfMjYG9WKTnS9TTEBlKtPV++W+qtGvfWPELi9wtnKg/yjf09B+dOX8FyGSr8izORFeOrN7pGsk1TgbObKxcnVI64DcDLRNL2ognt5CZTU4B7TYLnC8Dos/N0r0Fs8hY+OcCP6eUXiANhCooyISo0Z4LKAOmU0YvaldXSMX2o2GUioguHmcj0qa/Gn+f7PqXX3jUrZcoYJnQ2fHsANfGP9NPi8UbCxIR7d1ranXuHIAIQ7PFw+nCqMw0xfD3NrLduH0sgafVC2FiKrL923tlJcUoSpOnGqrgOCLVgaHfUoYHpfMWPCV2Ay02szxdWMSIQrMh71DU0l2Qa25QmGUnfmPl2G3glVxmtetDcYQNu3CWysx6JlTB5QnLb47cSJp24c5s80ao4LcEKcgAQungCTz1JLErKMrrjM+uI7Dwi8pIygkJeH9VJn7Ic3HwG/u7EAo8j+afnSeVuBWFJMc8DIuKC6FGIPdepbg2TVIy+8eIue5V4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
